version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4567:4567'
    command: 'bundle exec rackup -p 4567 --host 0.0.0.0'
    restart: always
    volumes:
      - '.:/app'
